### ISSUE TITLE
Change dates in api calls to be user provided and then default to system time

### ISSUE THREAD

**Issue by j-palos** [j-palos/hacs-opensource#42]

**Comment by rquinones93** [comment]
Would you like me to change migrations so that Dates will be represented as a String of "Day/Month/Year" instead of the full Date object ie something like "2019-04-05 01:57:21"

or

Would you like me to just add a column to each table called `date` that adds the String I mentioned above, still keep 'createdAt' as the usual `new Date()`- the `date` table could then be updated with whatever value it may need, but `createdAt` will stay the same.

Which one would you rather I do? Honestly I'm leaning towards the latter.

**Comment by j-palos** [comment]
Leaning to the latter, but I'm concerned about being able to easily sort/filter by dates when not using actual date datatypes in sql. I guess you might know more about that.
